import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { CheckCircle2, ChevronRight, Clock3, FileSpreadsheet, Grid2X2, KeyRound, List, LogIn, LogOut, Pencil, Plus, Printer, RefreshCw, Rows3, RotateCcw, Save, Search, Share2, ShieldCheck, ShoppingCart, Trash2, Upload, User, UserPlus, X } from 'lucide-react'
import { categories, categoryOrder, sampleProducts } from './lib/sampleData'
import { checkCompatibility } from './lib/compatibility'
import { getProducts, rpc, supabaseConfigured } from './lib/supabase'
import { parseProductWorkbook } from './lib/importExcel'
import type { BuildSelection, CategoryKey, ImportedProduct, Product } from './types'

type QuoteSettings={company_name:string;hotline:string;email:string;address:string;website:string;notice:string;thank_you:string}
type UserAccountRow={id:string;username:string;is_active:boolean;password_ready:boolean;created_at:string;last_login_at:string|null}
type EmployeeSession={token:string;username:string}
type AdminRole='super_admin'|'sub_admin'
type AdminLoginRow={token:string;username:string;role:AdminRole}
type AdminSessionRow={valid:boolean;username:string;role:AdminRole}
type UserSessionRow={valid:boolean;username:string}
type QuoteHistoryRow={id:string;quote_code:string;employee_username?:string;customer_name:string;customer_phone:string;customer_address:string;customer_note:string;total:number;created_at:string;updated_at?:string;items:any[]}
type SampleConfig={id:string;name:string;description:string;total:number;items:any[];is_active:boolean;created_at:string}
type OrderRequest={id:string;request_code:string;employee_username?:string;customer_name:string;customer_phone:string;customer_address:string;customer_note:string;total:number;status:string;items:any[];created_at:string}

const money = (n:number) => new Intl.NumberFormat('vi-VN').format(n) + ' đ'
const today = () => new Intl.DateTimeFormat('vi-VN', { dateStyle: 'short', timeStyle: 'medium' }).format(new Date())
const defaultQuote:QuoteSettings={company_name:'CÔNG TY TNHH CÔNG NGHỆ NOVA TECH PC',hotline:'0377 455 855',email:'contact@novatechpc.vn',address:'134 Nguyễn Chính - Hoàng Mai - HN',website:'Novatechpc.vn',notice:'Giá bán, khuyến mãi của sản phẩm và tình trạng còn hàng có thể thay đổi bất cứ lúc nào mà không kịp báo trước.',thank_you:'NOVA TECH PC CHÂN THÀNH CẢM ƠN QUÝ KHÁCH'}
const errorMessage=(err:unknown)=>{const raw=err instanceof Error?err.message:String(err);try{const parsed=JSON.parse(raw);return parsed.message||raw}catch{return raw}}
const isInvalidCredentials=(err:unknown)=>errorMessage(err).toLowerCase().includes('sai tài khoản hoặc mật khẩu')
const emptyImage = 'https://placehold.co/400x300/f5f7fa/667085?text=Nova+Tech+PC'

function dbToProduct(p:any):Product {
  return { id:p.id, category:p.category, group_name:p.group_name, name:p.name, brand:p.brand || '', price:Number(p.sale_price ?? p.price ?? 0), image:p.image_url || emptyImage, stock:Number(p.stock || 0), warranty:p.warranty || '', specs:p.specs || {} }
}

export default function App(){
  const [build, setBuild] = useState<BuildSelection>(()=>{try{return JSON.parse(localStorage.getItem('pc-builder-draft')||'{}') as BuildSelection}catch{return {}}})
  const [active, setActive] = useState<CategoryKey | null>(null)
  const [search, setSearch] = useState('')
  const [brandFilter, setBrandFilter] = useState('')
  const [stockOnly, setStockOnly] = useState(true)
  const [minPrice, setMinPrice] = useState('')
  const [maxPrice, setMaxPrice] = useState('')
  const [sortBy, setSortBy] = useState<'recommended'|'price-asc'|'price-desc'|'stock-asc'|'name'>('recommended')
  const [budget, setBudget] = useState(30000000)
  const [products, setProducts] = useState<Product[]>(sampleProducts)
  const [adminAuthenticated,setAdminAuthenticated]=useState(()=>Boolean(localStorage.getItem('nova-admin-token')||sessionStorage.getItem('nova-admin-token')))
  const [adminRole,setAdminRole]=useState<AdminRole>(()=>((localStorage.getItem('nova-admin-role')||sessionStorage.getItem('nova-admin-role')) as AdminRole)||'sub_admin')
  const [adminUsername,setAdminUsername]=useState(()=>localStorage.getItem('nova-admin-username')||sessionStorage.getItem('nova-admin-username')||'Admin')
  const [quoteOpen, setQuoteOpen] = useState(false)
  const [userOpen,setUserOpen]=useState(false)
  const [historyOpen,setHistoryOpen]=useState(false)
  const [orderOpen,setOrderOpen]=useState(false)
  const [sampleConfigs,setSampleConfigs]=useState<SampleConfig[]>([])
  const [employee,setEmployee]=useState<EmployeeSession|null>(()=>{try{const token=localStorage.getItem('nova-user-token');const username=localStorage.getItem('nova-user-session-name');return token&&username?{token,username}:null}catch{return null}})
  const [viewMode,setViewMode]=useState<'grid'|'columns'|'rows'>('rows')
  const [pageTab,setPageTab]=useState<'admin'|'builder'|'guide'>('builder')
  const [quoteSettings,setQuoteSettings]=useState<QuoteSettings>(defaultQuote)

  useEffect(()=>{
    if (!supabaseConfigured) return
    rpc<QuoteSettings[]>('get_quote_settings',{}).then(r=>r?.[0]&&setQuoteSettings(r[0])).catch(console.warn)
    getProducts<any[]>().then(rows=>rows.length && setProducts(rows.map(dbToProduct).sort((a,b)=>categoryOrder[a.category]-categoryOrder[b.category] || a.name.localeCompare(b.name,'vi')))).catch(console.warn)
    rpc<SampleConfig[]>('public_list_sample_configs',{}).then(setSampleConfigs).catch(console.warn)
  },[])

  useEffect(()=>{
    if(!supabaseConfigured)return
    const adminToken=localStorage.getItem('nova-admin-token')||sessionStorage.getItem('nova-admin-token')
    const userToken=localStorage.getItem('nova-user-token')
    if(adminToken){rpc<AdminSessionRow[]>('validate_admin_session',{p_token:adminToken}).then(r=>{const row=r?.[0];if(!row?.valid)throw new Error('expired');setAdminAuthenticated(true);setAdminUsername(row.username);setAdminRole(row.role);localStorage.setItem('nova-admin-username',row.username);localStorage.setItem('nova-admin-role',row.role)}).catch(()=>{for(const k of ['nova-admin-token','nova-admin-role','nova-admin-username']){localStorage.removeItem(k);sessionStorage.removeItem(k)}setAdminAuthenticated(false);setPageTab('builder')})}
    if(userToken){rpc<UserSessionRow[]>('validate_user_session',{p_token:userToken}).then(r=>{const row=r?.[0];if(!row?.valid)throw new Error('expired');setEmployee({token:userToken,username:row.username});localStorage.setItem('nova-user-session-name',row.username)}).catch(()=>{localStorage.removeItem('nova-user-token');localStorage.removeItem('nova-user-session-name');setEmployee(null);setHistoryOpen(false)})}
  },[])

  const total = (Object.values(build) as Array<Product | undefined>).reduce((s,p)=>s+(p?.price||0),0)
  const compatibility = useMemo(()=>checkCompatibility(build),[build])
  const categoryProducts = useMemo(()=>products.filter(p=>p.category===active),[products,active])
  const brands = useMemo(()=>Array.from(new Set(categoryProducts.map(p=>p.brand).filter(Boolean))).sort((a,b)=>a.localeCompare(b,'vi')),[categoryProducts])
  const filtered = useMemo(()=>categoryProducts
    .filter(p=>p.name.toLowerCase().includes(search.toLowerCase()))
    .filter(p=>!brandFilter || p.brand===brandFilter)
    .filter(p=>!stockOnly || p.stock>0)
    .filter(p=>!minPrice || p.price>=Number(minPrice))
    .filter(p=>!maxPrice || p.price<=Number(maxPrice))
    .sort((a,b)=>{
      if(sortBy==='price-asc') return a.price-b.price
      if(sortBy==='price-desc') return b.price-a.price
      if(sortBy==='stock-asc') return a.stock-b.stock || a.price-b.price || a.name.localeCompare(b.name,'vi')
      if(sortBy==='name') return a.name.localeCompare(b.name,'vi')
      return Number(b.stock>0)-Number(a.stock>0) || b.stock-a.stock || a.price-b.price || a.name.localeCompare(b.name,'vi')
    }),[categoryProducts,search,brandFilter,stockOnly,minPrice,maxPrice,sortBy])
  const categoryCounts = useMemo(()=>Object.fromEntries(categories.map(c=>[c.key,products.filter(p=>p.category===c.key).length])) as Record<CategoryKey,number>,[products])

  function openCategory(category:CategoryKey){ setActive(category); setSearch(''); setBrandFilter(''); setStockOnly(true); setMinPrice(''); setMaxPrice(''); setSortBy('recommended') }
  function choose(p:Product){ setBuild(v=>({...v,[p.category]:p})); setActive(null); setSearch('') }
  function updateSelected(category:CategoryKey, changes:Partial<Pick<Product,'price'|'warranty'>>){ setBuild(v=>{const current=v[category];if(!current)return v;return {...v,[category]:{...current,...changes}}}) }
  function remove(category:CategoryKey){ setBuild(v=>{const n={...v}; delete n[category]; return n}) }
  function reset(){ if(confirm('Xóa toàn bộ linh kiện đã chọn?')) setBuild({}) }
  function share(){ navigator.clipboard.writeText(location.href + '#build=' + btoa(JSON.stringify(Object.fromEntries(Object.entries(build).map(([k,v])=>[k,v?.id]))))); alert('Đã sao chép liên kết cấu hình.') }
  function save(){ localStorage.setItem('pc-builder-draft',JSON.stringify(build)); alert('Đã lưu bản nháp cấu hình trên trình duyệt. Khi mở lại web, cấu hình này sẽ được khôi phục.') }
  async function logoutUser(){const token=employee?.token;try{if(token)await rpc('user_logout',{p_token:token})}catch{}finally{localStorage.removeItem('nova-user-token');localStorage.removeItem('nova-user-session-name');setEmployee(null);setHistoryOpen(false)}}
  async function logoutAdmin(){const token=localStorage.getItem('nova-admin-token')||sessionStorage.getItem('nova-admin-token');try{if(token)await rpc('admin_logout',{p_token:token})}catch{}finally{for(const k of ['nova-admin-token','nova-admin-role','nova-admin-username']){localStorage.removeItem(k);sessionStorage.removeItem(k)}setAdminAuthenticated(false);setPageTab('builder')}}

  return <div className="app">
    <header className="topbar">
      <div className="brand"><img src="/nova-tech-logo.png"/><div><b>NOVA TECH PC</b><span>Đối tác cho sự thành công của bạn</span></div></div>
      <nav>{adminAuthenticated&&<button className={pageTab==='admin'?'nav-tab admin-tab active':'nav-tab admin-tab'} onClick={()=>setPageTab('admin')}>Admin</button>}<button className={pageTab==='builder'?'nav-tab active':'nav-tab'} onClick={()=>setPageTab('builder')}>Build PC</button><button className={pageTab==='guide'?'nav-tab active':'nav-tab'} onClick={()=>setPageTab('guide')}>Hướng dẫn</button>{employee?<><button className="employee-history-btn" onClick={()=>setHistoryOpen(true)}><Clock3 size={16}/> Lịch sử báo giá</button><span className="user-login logged-in account-status"><span className="user-login-icon"><User size={17}/></span><span className="user-login-text"><b>{employee.username}</b></span></span><button className="logout-compact" onClick={logoutUser}><LogOut size={16}/> Đăng xuất</button></>:adminAuthenticated?<><span className="user-login logged-in account-status"><span className="user-login-icon"><ShieldCheck size={17}/></span><span className="user-login-text"><b>{adminUsername}</b></span></span><button className="logout-compact" onClick={logoutAdmin}><LogOut size={16}/> Đăng xuất</button></>:<button className="user-login" onClick={()=>setUserOpen(true)} aria-label="Đăng nhập"><span className="user-login-icon"><User size={17}/></span><span className="user-login-text"><b>Đăng nhập</b></span></button>}</nav>
    </header>

    {pageTab==='admin'&&adminAuthenticated&&<AdminPanel adminRole={adminRole} build={build} products={products} quoteSettings={quoteSettings} onQuoteSaved={setQuoteSettings} onAdminLogout={()=>{setAdminAuthenticated(false);setPageTab('builder')}} onClose={()=>setPageTab('builder')} onImported={()=>getProducts<any[]>().then(rows=>setProducts(rows.map(dbToProduct).sort((a,b)=>categoryOrder[a.category]-categoryOrder[b.category] || a.name.localeCompare(b.name,'vi'))))}/>}

    {pageTab==='builder'&&<>
    <section className="hero">
      <div><span className="eyebrow">CÔNG CỤ XÂY DỰNG CẤU HÌNH</span><h1>Tự chọn linh kiện,<br/>kiểm tra tương thích tức thì</h1><p>Dữ liệu sản phẩm được cập nhật trực tiếp từ file Excel của NOVA TECH PC.</p></div>
      <div className="budget-card"><label>Ngân sách dự kiến</label><strong>{money(budget)}</strong><input type="range" min="7000000" max="100000000" step="1000000" value={budget} onChange={e=>setBudget(+e.target.value)}/><div className="budget-status">Đã chọn {money(total)} • Còn lại {money(Math.max(0,budget-total))}</div></div>
    </section>

    {sampleConfigs.length>0&&<section className="sample-configs"><div className="sample-head"><div><span className="eyebrow">CẤU HÌNH MẪU</span><h2>Chọn nhanh cấu hình có sẵn</h2></div></div><div className="sample-grid">{sampleConfigs.map(sc=><article key={sc.id}><h3>{sc.name}</h3><p>{sc.description||'Cấu hình được NOVA TECH PC đề xuất.'}</p><strong>{money(Number(sc.total||0))}</strong><small>{(sc.items||[]).length} linh kiện</small><button onClick={()=>{const next:BuildSelection={};for(const item of sc.items||[]){const found=products.find(p=>p.id===item.product_id)||products.find(p=>p.name===item.name);if(found)next[found.category]=found}setBuild(next);setPageTab('builder');window.scrollTo({top:document.getElementById('builder')?.offsetTop||0,behavior:'smooth'})}}>Dùng cấu hình này</button></article>)}</div></section>}

    <main id="builder" className="layout">
      <section className="builder-panel">
        <div className="panel-head"><div><h2>Xây dựng cấu hình PC</h2><p>Chọn lần lượt từng nhóm linh kiện</p></div><button className="ghost" onClick={reset}><RotateCcw size={17}/> Làm mới</button></div>
        <div className="parts-list">
          {categories.map((c,i)=>{const p=build[c.key]; return <div className="part-row" key={c.key}>
            <div className="part-index">{i+1}</div>
            <div className="part-info"><div className="part-label">{c.label}</div>{p?<div className="selected selected-editable"><div className="selected-main"><b>{p.name}</b><small>Tồn kho: {p.stock}</small><div className="selected-edit-fields"><label><span>Giá bán</span><input type="number" min="0" step="1000" value={p.price} onChange={e=>updateSelected(c.key,{price:Math.max(0,Number(e.target.value)||0)})}/></label><label><span>Bảo hành</span><input type="text" value={p.warranty||''} placeholder="Ví dụ: 36 tháng" onChange={e=>updateSelected(c.key,{warranty:e.target.value})}/></label></div></div><strong>{money(p.price)}</strong><button className="remove-selected" onClick={()=>remove(c.key)} title="Xóa sản phẩm"><X size={18}/></button></div>:<button className="select-btn" onClick={()=>openCategory(c.key)}><span>+ Chọn linh kiện <small>{categoryCounts[c.key]||0} sản phẩm</small></span><ChevronRight size={18}/></button>}</div>
          </div>})}
        </div>
      </section>

      <aside className="summary">
        <h3>Tóm tắt cấu hình</h3>
        <div className="sum-line"><span>Chi phí linh kiện</span><b>{money(total)}</b></div>
        <div className="sum-line"><span>Phí lắp ráp</span><b>Miễn phí</b></div>
        <div className="total"><span>Tổng thanh toán</span><strong>{money(total)}</strong></div>
        <div className="compat"><h4><ShieldCheck size={18}/> Kiểm tra tương thích</h4>{compatibility.map((r,i)=><div key={i} className={'notice '+r.level}><CheckCircle2 size={16}/><span>{r.message}</span></div>)}</div>
        <button className="primary" disabled={!Object.keys(build).length} onClick={()=>setOrderOpen(true)}><ShoppingCart size={19}/> Gửi yêu cầu đặt hàng</button>
        <button className="quote-button" disabled={!Object.keys(build).length} onClick={()=>setQuoteOpen(true)}><Printer size={18}/> Xem/In báo giá</button>
        <div className="actions"><button onClick={save}><Save size={17}/> Lưu</button><button onClick={share}><Share2 size={17}/> Chia sẻ</button></div>
        <small className="hint">Có thể chọn một linh kiện lẻ hoặc nhiều linh kiện tùy nhu cầu.</small>
      </aside>
    </main>

    </>}
    {pageTab==='guide'&&<GuideTab onStart={()=>setPageTab('builder')}/>}

    {active&&<div className="modal-backdrop" onClick={()=>setActive(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><h2>{categories.find(c=>c.key===active)?.label}</h2><p>{categoryProducts.length} sản phẩm đã được phân loại vào đúng danh mục</p></div><button onClick={()=>setActive(null)}><X/></button></div>
      <div className="catalog-tools"><input className="search" placeholder="Tìm theo tên sản phẩm..." value={search} onChange={e=>setSearch(e.target.value)}/><select value={brandFilter} onChange={e=>setBrandFilter(e.target.value)}><option value="">Tất cả thương hiệu</option>{brands.map(b=><option key={b}>{b}</option>)}</select><input type="number" min="0" placeholder="Giá từ" value={minPrice} onChange={e=>setMinPrice(e.target.value)}/><input type="number" min="0" placeholder="Giá đến" value={maxPrice} onChange={e=>setMaxPrice(e.target.value)}/><select value={sortBy} onChange={e=>setSortBy(e.target.value as typeof sortBy)}><option value="recommended">Ưu tiên còn hàng</option><option value="price-asc">Giá thấp đến cao</option><option value="price-desc">Giá cao đến thấp</option><option value="stock-asc">Tồn kho ít đến nhiều</option><option value="name">Tên A-Z</option></select><label className="stock-check"><input type="checkbox" checked={stockOnly} onChange={e=>setStockOnly(e.target.checked)}/> Chỉ còn hàng</label></div>
      <div className="filter-result"><span>Đang hiển thị <b>{filtered.length}</b> / {categoryProducts.length} sản phẩm</span><div className="view-switch"><button className={viewMode==='grid'?'active':''} onClick={()=>setViewMode('grid')} title="Lưới"><Grid2X2 size={17}/><span>Lưới</span></button><button className={viewMode==='columns'?'active':''} onClick={()=>setViewMode('columns')} title="Cột gọn"><List size={17}/><span>Cột</span></button><button className={viewMode==='rows'?'active':''} onClick={()=>setViewMode('rows')} title="Hàng ngang"><Rows3 size={17}/><span>Hàng ngang</span></button></div></div><div className={`product-grid ${viewMode}`}> {filtered.map(p=><article className="product" key={p.id}><div className={'stock '+(p.stock<=0?'out':'')}>{p.stock>0?`Còn ${p.stock}`:'Hết hàng'}</div><div className="group-tag">{p.group_name || categories.find(c=>c.key===p.category)?.shortLabel}</div><h3>{p.name}</h3><p>{p.warranty || 'Bảo hành: đang cập nhật'}</p><strong>{money(p.price)}</strong><button disabled={p.stock<=0} onClick={()=>choose(p)}>{p.stock>0?'Chọn sản phẩm':'Tạm hết hàng'}</button></article>)}</div>{!filtered.length&&<div className="empty">Không có sản phẩm phù hợp với bộ lọc hiện tại.</div>}</div></div>}
    {userOpen&&<UserLogin onClose={()=>setUserOpen(false)} onLoggedIn={v=>{for(const k of ['nova-admin-token','nova-admin-role','nova-admin-username']){localStorage.removeItem(k);sessionStorage.removeItem(k)}setAdminAuthenticated(false);setEmployee(v);setUserOpen(false)}} onAdminLoggedIn={a=>{localStorage.removeItem('nova-user-token');localStorage.removeItem('nova-user-session-name');setEmployee(null);setAdminRole(a.role);setAdminUsername(a.username);setAdminAuthenticated(true);setUserOpen(false);setPageTab('admin')}}/>}
    {quoteOpen&&<Quote settings={quoteSettings} build={build} total={total} employee={employee} onNeedLogin={()=>{setQuoteOpen(false);setUserOpen(true)}} onClose={()=>setQuoteOpen(false)}/>} 
    {historyOpen&&employee&&<QuoteHistory employee={employee} onClose={()=>setHistoryOpen(false)}/>}
    {orderOpen&&<OrderRequestDialog settings={quoteSettings} build={build} total={total} employee={employee} onNeedLogin={()=>{setOrderOpen(false);setUserOpen(true)}} onClose={()=>setOrderOpen(false)}/>} 
  </div>
}

function GuideTab({onStart}:{onStart:()=>void}){
  return <main className="guide-page">
    <section className="guide-hero"><span className="eyebrow">HƯỚNG DẪN SỬ DỤNG</span><h1>Tạo cấu hình và báo giá chỉ trong vài bước</h1><p>Quy trình dành cho NOVA TECH PC: chọn linh kiện, kiểm tra cấu hình, nhập thông tin khách hàng, lưu và in báo giá.</p><button className="primary guide-start" onClick={onStart}><ShoppingCart size={18}/> Bắt đầu Build PC</button></section>
    <section className="guide-steps">
      <article><b>01</b><div><h3>Đăng nhập tài khoản</h3><p>Bấm <strong>Đăng nhập</strong> trên thanh menu. Tài khoản được Admin cấp và dùng để lưu lịch sử báo giá.</p></div></article>
      <article><b>02</b><div><h3>Chọn từng nhóm linh kiện</h3><p>Chọn CPU, Mainboard, RAM, ổ cứng, nguồn, case và các linh kiện tùy chọn. Có thể tìm kiếm, lọc tồn kho và sắp xếp theo giá.</p></div></article>
      <article><b>03</b><div><h3>Kiểm tra tổng tiền và tương thích</h3><p>Khung bên phải hiển thị tổng tiền, ngân sách còn lại và các cảnh báo tương thích cơ bản.</p></div></article>
      <article><b>04</b><div><h3>Nhập thông tin khách hàng</h3><p>Bấm <strong>Xem/In báo giá</strong>, nhập tên khách hàng, số điện thoại, địa chỉ và ghi chú.</p></div></article>
      <article><b>05</b><div><h3>Lưu hoặc Lưu & In</h3><p>Mỗi báo giá được lưu vào lịch sử tài khoản. Giá và tên sản phẩm được giữ theo thời điểm lập báo giá.</p></div></article>
      <article><b>06</b><div><h3>Quản lý lịch sử</h3><p>Mở <strong>Lịch sử báo giá</strong> để xem chi tiết, sửa thông tin, cập nhật sản phẩm hoặc xóa báo giá.</p></div></article>
    </section>
    <section className="guide-notes"><h2>Lưu ý quan trọng</h2><div><p><b>Dữ liệu sản phẩm:</b> Admin cập nhật bằng Excel gồm Nhóm hàng, Tên hàng, Giá bán, Tồn kho và Bảo hành.</p><p><b>Báo giá cũ:</b> Không tự đổi theo giá Excel mới; đây là bản chụp tại thời điểm lưu.</p><p><b>Mật khẩu:</b> Trình duyệt có thể lưu mật khẩu; hệ thống không hiển thị lại mật khẩu trong phần quản trị.</p></div></section>
  </main>
}

function AdminPanel({adminRole,onClose,onImported,quoteSettings,onQuoteSaved,onAdminLogout,build,products}:{adminRole:AdminRole,onClose:()=>void,onImported:()=>void,quoteSettings:QuoteSettings,onQuoteSaved:(v:QuoteSettings)=>void,onAdminLogout:()=>void,build:BuildSelection,products:Product[]}){
  const [token,setToken]=useState(()=>localStorage.getItem('nova-admin-token')||sessionStorage.getItem('nova-admin-token')||'')
  const [username,setUsername]=useState(()=>localStorage.getItem('nova-admin-user')||'admin');const [password,setPassword]=useState('');const [rememberAdmin,setRememberAdmin]=useState(()=>localStorage.getItem('nova-admin-user')!==null)
  const [tab,setTab]=useState<'products'|'users'|'quotes'|'orders'|'samples'|'settings'|'admins'>('products');const [status,setStatus]=useState('')
  const [rows,setRows]=useState<ImportedProduct[]>([]);const [fileName,setFileName]=useState('');const [users,setUsers]=useState<UserAccountRow[]>([]);const [quotes,setQuotes]=useState<QuoteHistoryRow[]>([]);const [orders,setOrders]=useState<OrderRequest[]>([]);const [samples,setSamples]=useState<SampleConfig[]>([])
  const [search,setSearch]=useState('');const [selectedQuote,setSelectedQuote]=useState<QuoteHistoryRow|null>(null);const [selectedOrder,setSelectedOrder]=useState<OrderRequest|null>(null)
  const [newCustomer,setNewCustomer]=useState('');const [newCustomerPass,setNewCustomerPass]=useState('');const [newAdmin,setNewAdmin]=useState('');const [newAdminPass,setNewAdminPass]=useState('');const [sampleName,setSampleName]=useState('');const [sampleDescription,setSampleDescription]=useState('');const [quoteForm,setQuoteForm]=useState<QuoteSettings>(quoteSettings)
  async function login(e:FormEvent){e.preventDefault();try{const r=await rpc<AdminLoginRow[]>('admin_login',{p_username:username,p_password:password});const t=r?.[0]?.token;if(!t)throw new Error('Sai tài khoản hoặc mật khẩu');localStorage.setItem('nova-admin-token',t);localStorage.setItem('nova-admin-role',r[0].role);localStorage.setItem('nova-admin-username',r[0].username);sessionStorage.removeItem('nova-admin-token');sessionStorage.removeItem('nova-admin-role');sessionStorage.removeItem('nova-admin-username');if(rememberAdmin)localStorage.setItem('nova-admin-user',username);setToken(t);setPassword('');setStatus('Đăng nhập thành công')}catch(err){setStatus('Đăng nhập thất bại: '+String(err))}}
  async function loadUsers(){if(token)setUsers(await rpc<UserAccountRow[]>('admin_list_user_accounts',{p_token:token})||[])}
  async function loadQuotes(){if(token)setQuotes(await rpc<QuoteHistoryRow[]>('admin_list_quote_history',{p_token:token,p_search:search.trim()||null})||[])}
  async function loadOrders(){if(token)setOrders(await rpc<OrderRequest[]>('admin_list_order_requests',{p_token:token,p_search:search.trim()||null})||[])}
  async function loadSamples(){if(token)setSamples(await rpc<SampleConfig[]>('admin_list_sample_configs',{p_token:token})||[])}
  useEffect(()=>{if(token){loadUsers();loadQuotes();loadOrders();loadSamples()}},[token])
  async function pick(file?:File){if(!file)return;try{const data=await parseProductWorkbook(file);setRows(data);setFileName(file.name);setStatus(`Đã đọc ${data.length} sản phẩm.`)}catch(err){setStatus('Không đọc được file: '+String(err))}}
  async function importNow(){try{await rpc('admin_import_products',{p_token:token,p_rows:rows});setStatus(`Đã cập nhật ${rows.length} sản phẩm.`);onImported()}catch(err){setStatus('Nhập dữ liệu thất bại: '+String(err))}}
  async function createUser(e:FormEvent){e.preventDefault();try{await rpc('admin_create_user_account',{p_token:token,p_username:newCustomer,p_password:newCustomerPass});setNewCustomer('');setNewCustomerPass('');setStatus('Đã tạo tài khoản.');loadUsers()}catch(err){setStatus('Không tạo được tài khoản: '+String(err))}}
  async function resetPass(u:UserAccountRow){const v=prompt('Nhập mật khẩu mới (tối thiểu 6 ký tự)');if(!v||v.length<6)return;try{await rpc('admin_reset_user_password',{p_token:token,p_user_id:u.id,p_new_password:v});setStatus('Đã cấp mật khẩu mới.')}catch(err){setStatus(String(err))}}
  async function toggle(u:UserAccountRow){await rpc('admin_update_user_account',{p_token:token,p_user_id:u.id,p_username:null,p_is_active:!u.is_active});loadUsers()}
  async function removeUser(u:UserAccountRow){if(confirm('Xóa tài khoản '+u.username+'?')){await rpc('admin_delete_user_account',{p_token:token,p_user_id:u.id});loadUsers()}}
  async function createAdmin(e:FormEvent){e.preventDefault();try{await rpc('admin_create_account',{p_token:token,p_username:newAdmin,p_password:newAdminPass});setStatus('Đã tạo tài khoản Admin phụ.');setNewAdmin('');setNewAdminPass('')}catch(err){setStatus(String(err))}}
  async function saveSettings(e:FormEvent){e.preventDefault();await rpc('admin_update_quote_settings',{p_token:token,p_settings:quoteForm});onQuoteSaved(quoteForm);setStatus('Đã lưu mẫu báo giá.')}
  async function saveSample(e:FormEvent){e.preventDefault();const items=(Object.values(build).filter(Boolean) as Product[]).map(p=>({product_id:p.id,category:p.category,name:p.name,warranty:p.warranty,unit_price:p.price,quantity:1}));if(!items.length){setStatus('Hãy chọn ít nhất một linh kiện ở tab Build PC trước.');return}await rpc('admin_save_sample_config',{p_token:token,p_name:sampleName,p_description:sampleDescription,p_items:items,p_total:items.reduce((s,x)=>s+Number(x.unit_price),0)});setSampleName('');setSampleDescription('');setStatus('Đã lưu cấu hình mẫu.');loadSamples()}
  async function removeSample(id:string){if(confirm('Xóa cấu hình mẫu này?')){await rpc('admin_delete_sample_config',{p_token:token,p_config_id:id});loadSamples()}}
  async function updateOrder(id:string,statusValue:string){await rpc('admin_update_order_request_status',{p_token:token,p_request_id:id,p_status:statusValue});loadOrders()}
  async function logout(){try{if(token)await rpc('admin_logout',{p_token:token})}catch{}finally{for(const k of ['nova-admin-token','nova-admin-role','nova-admin-username']){localStorage.removeItem(k);sessionStorage.removeItem(k)}setToken('');onAdminLogout()}}
  const tabs:Array<[typeof tab,string]>=[['products','Sản phẩm'],['users','Tài khoản'],['quotes','Báo giá'],['orders','Yêu cầu đặt hàng'],['samples','Cấu hình mẫu'],['settings','Mẫu báo giá']];if(adminRole==='super_admin')tabs.push(['admins','Admin phụ'])
  return <main className="admin-page"><section className="admin-panel admin-workspace"><div className="admin-page-head"><div><span className="eyebrow">QUẢN TRỊ HỆ THỐNG</span><h1>Admin</h1><p>Quản trị sản phẩm, tài khoản, báo giá, yêu cầu đặt hàng và cấu hình mẫu.</p></div></div>{!token?<form className="login-form" onSubmit={login}><label>Tên đăng nhập<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>Mật khẩu<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><label className="remember-login"><input type="checkbox" checked={rememberAdmin} onChange={e=>setRememberAdmin(e.target.checked)}/> Ghi nhớ tên đăng nhập</label><button className="primary"><LogIn size={18}/> Đăng nhập</button></form>:<><div className="admin-toolbar"><div className="admin-tabs">{tabs.map(([k,l])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{l}</button>)}</div><button onClick={logout}><LogOut size={16}/> Đăng xuất</button></div><div className="admin-body">
  {tab==='products'&&<section className="admin-card"><h3><Upload size={19}/> Nhập danh sách sản phẩm</h3><label className="upload-box"><input type="file" accept=".xlsx,.xls" onChange={e=>pick(e.target.files?.[0])}/><FileSpreadsheet size={28}/><b>{fileName||'Chọn file Excel'}</b></label>{rows.length>0&&<><p>Đã đọc {rows.length} sản phẩm.</p><button className="primary" onClick={importNow}>Cập nhật sản phẩm</button></>}</section>}
  {tab==='users'&&<section className="admin-card"><h3>Quản lý tài khoản</h3><form className="account-form" onSubmit={createUser}><input placeholder="Tên tài khoản" value={newCustomer} onChange={e=>setNewCustomer(e.target.value)} required/><input type="password" placeholder="Mật khẩu" value={newCustomerPass} onChange={e=>setNewCustomerPass(e.target.value)} required/><button>Tạo</button></form><div className="user-admin-table"><table><thead><tr><th>Tài khoản</th><th>Trạng thái</th><th>Ngày tạo</th><th>Thao tác</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.username}</b></td><td>{u.is_active?'Hoạt động':'Đã khóa'}</td><td>{new Date(u.created_at).toLocaleString('vi-VN')}</td><td><div className="history-actions"><button onClick={()=>resetPass(u)}>Cấp mật khẩu</button><button onClick={()=>toggle(u)}>{u.is_active?'Khóa':'Mở khóa'}</button><button className="danger" onClick={()=>removeUser(u)}>Xóa</button></div></td></tr>)}</tbody></table></div></section>}
  {tab==='quotes'&&<section className="admin-card"><h3>Lịch sử báo giá</h3><div className="history-tools"><div><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm theo tài khoản, khách hàng, số điện thoại"/></div><button onClick={loadQuotes}>Tìm</button></div><div className="history-table"><table><thead><tr><th>Tài khoản</th><th>Khách hàng</th><th>SĐT</th><th>Tổng</th><th>Ngày</th><th></th></tr></thead><tbody>{quotes.map(q=><tr key={q.id}><td>{q.employee_username}</td><td>{q.customer_name}</td><td>{q.customer_phone||'-'}</td><td>{money(Number(q.total))}</td><td>{new Date(q.created_at).toLocaleString('vi-VN')}</td><td><button onClick={()=>setSelectedQuote(q)}>Xem</button></td></tr>)}</tbody></table></div>{selectedQuote&&<QuoteDetail row={selectedQuote} onClose={()=>setSelectedQuote(null)}/>}</section>}
  {tab==='orders'&&<section className="admin-card"><h3>Yêu cầu đặt hàng</h3><div className="history-tools"><div><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm khách hàng, SĐT hoặc tài khoản"/></div><button onClick={loadOrders}>Tìm</button></div><div className="history-table"><table><thead><tr><th>Mã</th><th>Tài khoản</th><th>Khách hàng</th><th>Tổng</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.request_code}</td><td>{o.employee_username||'Khách'}</td><td>{o.customer_name}</td><td>{money(Number(o.total))}</td><td>{o.status}</td><td><div className="history-actions"><button onClick={()=>setSelectedOrder(o)}>Xem</button><select value={o.status} onChange={e=>updateOrder(o.id,e.target.value)}><option value="new">Mới</option><option value="contacted">Đã liên hệ</option><option value="completed">Hoàn tất</option><option value="cancelled">Đã hủy</option></select></div></td></tr>)}</tbody></table></div>{selectedOrder&&<div className="history-detail"><div><h3>{selectedOrder.request_code} — {selectedOrder.customer_name}</h3><button onClick={()=>setSelectedOrder(null)}><X size={16}/></button></div><p>{selectedOrder.customer_phone} • {selectedOrder.customer_address}</p><ul>{(selectedOrder.items||[]).map((x:any,i:number)=><li key={i}><span>{x.name}</span><b>{money(Number(x.line_total||x.unit_price||0))}</b></li>)}</ul></div>}</section>}
  {tab==='samples'&&<section className="admin-card"><h3>Cấu hình mẫu</h3><p>Chọn linh kiện ở tab Build PC, sau đó quay lại đây để lưu thành cấu hình mẫu.</p><form className="account-form" onSubmit={saveSample}><input placeholder="Tên cấu hình mẫu" value={sampleName} onChange={e=>setSampleName(e.target.value)} required/><input placeholder="Mô tả" value={sampleDescription} onChange={e=>setSampleDescription(e.target.value)}/><button>Lưu cấu hình hiện tại</button></form><div className="sample-admin-list">{samples.map(x=><div key={x.id}><div><b>{x.name}</b><small>{x.description} • {(x.items||[]).length} linh kiện • {money(Number(x.total))}</small></div><button className="danger" onClick={()=>removeSample(x.id)}>Xóa</button></div>)}</div></section>}
  {tab==='settings'&&<section className="admin-card quote-settings"><h3>Chỉnh sửa mẫu báo giá</h3><form onSubmit={saveSettings}><label>Tên công ty<input value={quoteForm.company_name} onChange={e=>setQuoteForm({...quoteForm,company_name:e.target.value})}/></label><label>Hotline<input value={quoteForm.hotline} onChange={e=>setQuoteForm({...quoteForm,hotline:e.target.value})}/></label><label>Email<input value={quoteForm.email} onChange={e=>setQuoteForm({...quoteForm,email:e.target.value})}/></label><label>Địa chỉ<input value={quoteForm.address} onChange={e=>setQuoteForm({...quoteForm,address:e.target.value})}/></label><label>Website<input value={quoteForm.website} onChange={e=>setQuoteForm({...quoteForm,website:e.target.value})}/></label><label>Lưu ý<textarea value={quoteForm.notice} onChange={e=>setQuoteForm({...quoteForm,notice:e.target.value})}/></label><button className="primary">Lưu</button></form></section>}
  {tab==='admins'&&adminRole==='super_admin'&&<section className="admin-card"><h3>Tạo tài khoản Admin phụ</h3><p>Admin phụ có đầy đủ quyền quản trị, trừ quyền tạo thêm tài khoản Admin.</p><form className="account-form" onSubmit={createAdmin}><input placeholder="Tên tài khoản" value={newAdmin} onChange={e=>setNewAdmin(e.target.value)} required/><input type="password" placeholder="Mật khẩu" value={newAdminPass} onChange={e=>setNewAdminPass(e.target.value)} required/><button>Tạo Admin phụ</button></form></section>}
</div></>}{status&&<div className="admin-status">{status}</div>}</section></main>
}

function UserLogin({onClose,onLoggedIn,onAdminLoggedIn}:{onClose:()=>void,onLoggedIn:(v:EmployeeSession)=>void,onAdminLoggedIn:(v:AdminLoginRow)=>void}){
  const [username,setUsername]=useState(()=>localStorage.getItem('nova-user-name')||'');const [password,setPassword]=useState('');const [remember,setRemember]=useState(Boolean(localStorage.getItem('nova-user-name')));const [status,setStatus]=useState('')
  async function login(e:FormEvent){e.preventDefault();setStatus('Đang đăng nhập...');const normalized=username.trim();try{try{const adminResult=await rpc<AdminLoginRow[]>('admin_login',{p_username:normalized,p_password:password});const row=adminResult?.[0];if(row?.token){localStorage.setItem('nova-admin-token',row.token);localStorage.setItem('nova-admin-role',row.role);localStorage.setItem('nova-admin-username',row.username);sessionStorage.removeItem('nova-admin-token');sessionStorage.removeItem('nova-admin-role');sessionStorage.removeItem('nova-admin-username');if(remember)localStorage.setItem('nova-admin-user',normalized);setPassword('');onAdminLoggedIn(row);return}}catch(adminErr){if(!isInvalidCredentials(adminErr))throw adminErr}const r=await rpc<{token:string;username:string}[]>('user_login',{p_username:normalized,p_password:password});if(!r?.[0]?.token)throw new Error('Sai tài khoản hoặc mật khẩu');const session={token:r[0].token,username:r[0].username||normalized.toLowerCase()};localStorage.setItem('nova-user-token',session.token);localStorage.setItem('nova-user-session-name',session.username);if(remember)localStorage.setItem('nova-user-name',normalized);else localStorage.removeItem('nova-user-name');setPassword('');onLoggedIn(session)}catch(err){setStatus('Đăng nhập thất bại: '+errorMessage(err))}}
  return <div className="modal-backdrop customer-login-backdrop"><div className="customer-login-dialog"><button className="customer-login-close" onClick={onClose} aria-label="Đóng"><X/></button><section className="customer-login-brand"><img src="/nova-tech-logo.png"/><span className="customer-login-eyebrow">NOVA TECH PC</span><h2>Đăng nhập tài khoản</h2><p>Đăng nhập để sử dụng các chức năng được cấp cho tài khoản.</p><div className="customer-login-points"><span><CheckCircle2 size={17}/> Lưu báo giá theo khách hàng</span><span><CheckCircle2 size={17}/> Xem, sửa hoặc xóa báo giá đã lưu</span><span><CheckCircle2 size={17}/> Tìm nhanh theo tên, số điện thoại hoặc mã báo giá</span></div></section><form className="customer-login-form" onSubmit={login}><div className="customer-login-title"><User size={22}/><div><b>Đăng nhập</b><small>Sử dụng tài khoản được cấp</small></div></div><label>Tên đăng nhập<div className="login-input-wrap"><User size={18}/><input autoFocus autoComplete="username" placeholder="Nhập tên tài khoản" value={username} onChange={e=>setUsername(e.target.value)} required/></div></label><label>Mật khẩu<div className="login-input-wrap"><KeyRound size={18}/><input type="password" autoComplete="current-password" placeholder="Nhập mật khẩu" value={password} onChange={e=>setPassword(e.target.value)} required/></div></label><label className="remember-login customer-remember"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/> Ghi nhớ tên đăng nhập</label><button className="customer-login-submit"><LogIn size={18}/> Đăng nhập</button>{status&&<div className="admin-status">{status}</div>}</form></div></div>
}

function Quote({settings,build,total,employee,onNeedLogin,onClose}:{settings:QuoteSettings,build:BuildSelection,total:number,employee:EmployeeSession|null,onNeedLogin:()=>void,onClose:()=>void}){
  const items=Object.values(build).filter(Boolean) as Product[]
  const [customerName,setCustomerName]=useState('');const [customerPhone,setCustomerPhone]=useState('');const [customerAddress,setCustomerAddress]=useState('');const [customerNote,setCustomerNote]=useState('');const [status,setStatus]=useState('');const [savedCode,setSavedCode]=useState('')
  async function saveQuote(printAfter=false){if(!employee){onNeedLogin();return}if(!customerName.trim()){setStatus('Vui lòng nhập tên khách hàng.');return}setStatus('Đang lưu báo giá...');try{const payload=items.map(p=>({product_id:p.id,category:p.category,name:p.name,warranty:p.warranty,quantity:1,unit_price:p.price,line_total:p.price}));const r=await rpc<{quote_code:string}[]>('employee_save_quote',{p_token:employee.token,p_customer_name:customerName.trim(),p_customer_phone:customerPhone.trim(),p_customer_address:customerAddress.trim(),p_customer_note:customerNote.trim(),p_items:payload,p_total:total,p_quote_settings:settings});const code=r?.[0]?.quote_code||'';setSavedCode(code);setStatus('Đã lưu báo giá '+code+' vào lịch sử.');if(printAfter)setTimeout(()=>window.print(),150)}catch(err){setStatus('Không lưu được báo giá: '+String(err))}}
  return <div className="modal-backdrop quote-backdrop"><div className="quote-shell"><div className="quote-actions"><button onClick={onClose}><X size={17}/> Đóng</button>{employee?<><button onClick={()=>saveQuote(false)}><Save size={17}/> Lưu báo giá</button><button className="primary-inline" onClick={()=>saveQuote(true)}><Printer size={17}/> Lưu & In</button></>:<button className="primary-inline" onClick={onNeedLogin}><LogIn size={17}/> Đăng nhập để lưu</button>}</div><div className="quote-customer-form"><label>Tên khách hàng *<input value={customerName} onChange={e=>setCustomerName(e.target.value)} placeholder="Ví dụ: Nguyễn Văn A"/></label><label>Số điện thoại<input value={customerPhone} onChange={e=>setCustomerPhone(e.target.value)} placeholder="09..."/></label><label>Địa chỉ<input value={customerAddress} onChange={e=>setCustomerAddress(e.target.value)} placeholder="Địa chỉ giao hàng"/></label><label>Ghi chú<input value={customerNote} onChange={e=>setCustomerNote(e.target.value)} placeholder="Nhu cầu, thời gian hẹn..."/></label></div>{status&&<div className="quote-save-status">{status}</div>}<article className="quotation">
    <header className="quote-header"><div><h3>{settings.company_name}</h3><p><b>Trụ sở:</b> {settings.address}</p><p><b>Hotline:</b> {settings.hotline} &nbsp; | &nbsp; <b>Email:</b> {settings.email}</p><p><b>Website:</b> {settings.website}</p></div><img src="/nova-tech-logo.png"/></header><div className="green-line"/><h1>BÁO GIÁ SẢN PHẨM</h1><div className="quote-meta"><span>Ngày báo giá: <b>{today()}</b></span><span>Đơn vị tính: <b>VNĐ</b></span></div>{customerName&&<div className="quote-customer"><b>Khách hàng: {customerName}</b>{customerPhone&&<span> • SĐT: {customerPhone}</span>}{customerAddress&&<span> • Địa chỉ: {customerAddress}</span>}</div>}
    <table><thead><tr><th>STT</th><th>TÊN SẢN PHẨM</th><th>BẢO HÀNH</th><th>SỐ LƯỢNG</th><th>ĐƠN GIÁ</th><th>THÀNH TIỀN</th></tr></thead><tbody>{items.map((p,i)=><tr key={p.id}><td>{i+1}</td><td>{p.name}</td><td>{p.warranty||'Theo chính sách NSX'}</td><td>1</td><td>{new Intl.NumberFormat('vi-VN').format(p.price)}</td><td>{new Intl.NumberFormat('vi-VN').format(p.price)}</td></tr>)}{Array.from({length:Math.max(0,8-items.length)}).map((_,i)=><tr key={'blank'+i}><td>&nbsp;</td><td></td><td></td><td></td><td></td><td></td></tr>)}</tbody><tfoot><tr><td colSpan={4} rowSpan={4} className="quote-note"></td><td>Phí vận chuyển</td><td>0</td></tr><tr><td>Chi phí khác</td><td>0</td></tr><tr><td>Tổng tiền đơn hàng</td><td>{new Intl.NumberFormat('vi-VN').format(total)}</td></tr><tr className="grand"><td>TỔNG THANH TOÁN</td><td>{new Intl.NumberFormat('vi-VN').format(total)} VNĐ</td></tr></tfoot></table>
    <p className="customer-note"><b>Quý khách lưu ý:</b> {settings.notice}</p><footer><span>Để biết thêm chi tiết, vui lòng liên hệ<br/><b>Hotline: {settings.hotline}</b> (8h00 - 21h00 hàng ngày)</span><b>{settings.thank_you}</b></footer>
  </article></div></div>
}

function OrderRequestDialog({settings,build,total,employee,onNeedLogin,onClose}:{settings:QuoteSettings,build:BuildSelection,total:number,employee:EmployeeSession|null,onNeedLogin:()=>void,onClose:()=>void}){
 const items=Object.values(build).filter(Boolean) as Product[];const [name,setName]=useState('');const [phone,setPhone]=useState('');const [address,setAddress]=useState('');const [note,setNote]=useState('');const [status,setStatus]=useState('')
 async function send(){if(!name.trim()||!phone.trim()){setStatus('Vui lòng nhập tên khách hàng và số điện thoại.');return}try{const payload=items.map(p=>({product_id:p.id,category:p.category,name:p.name,warranty:p.warranty,quantity:1,unit_price:p.price,line_total:p.price}));const r=await rpc<{request_code:string}[]>('create_order_request',{p_token:employee?.token||null,p_customer_name:name.trim(),p_customer_phone:phone.trim(),p_customer_address:address.trim(),p_customer_note:note.trim(),p_items:payload,p_total:total});setStatus('Đã gửi yêu cầu '+(r?.[0]?.request_code||'')+' tới Admin.')}catch(err){setStatus('Không gửi được yêu cầu: '+String(err))}}
 return <div className="modal-backdrop"><div className="order-dialog"><div className="modal-head"><div><h2>Gửi yêu cầu đặt hàng</h2><p>Yêu cầu sẽ xuất hiện trong tab Admin.</p></div><button onClick={onClose}><X/></button></div><div className="quote-customer-form"><label>Tên khách hàng *<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Số điện thoại *<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Địa chỉ<input value={address} onChange={e=>setAddress(e.target.value)}/></label><label>Ghi chú<input value={note} onChange={e=>setNote(e.target.value)}/></label></div><div className="order-summary"><b>{items.length} sản phẩm</b><strong>{money(total)}</strong></div><button className="primary" onClick={send}><ShoppingCart size={18}/> Gửi tới Admin</button>{status&&<div className="admin-status">{status}</div>}</div></div>
}

function QuoteDetail({row,onClose}:{row:QuoteHistoryRow,onClose:()=>void}){
  return <div className="history-detail"><div><h3>{row.quote_code} — {row.customer_name}</h3><button onClick={onClose}><X size={16}/></button></div><p>{row.employee_username&&<>Tài khoản: <b>{row.employee_username}</b> • </>}{row.customer_phone&&<>SĐT: <b>{row.customer_phone}</b> • </>}{row.customer_address}</p>{row.customer_note&&<p>Ghi chú: {row.customer_note}</p>}<ul>{(row.items||[]).map((x:any,i:number)=><li key={i}><span>{x.name} × {Number(x.quantity||1)}</span><b>{money(Number(x.line_total||Number(x.unit_price||0)*Number(x.quantity||1)))}</b></li>)}</ul><strong>Tổng: {money(Number(row.total))}</strong></div>
}

function QuoteHistory({employee,onClose}:{employee:EmployeeSession,onClose:()=>void}){
  const [rows,setRows]=useState<QuoteHistoryRow[]>([]);const [search,setSearch]=useState('');const [status,setStatus]=useState('Đang tải lịch sử...');const [selected,setSelected]=useState<QuoteHistoryRow|null>(null);const [editing,setEditing]=useState<QuoteHistoryRow|null>(null)
  async function load(){try{const r=await rpc<QuoteHistoryRow[]>('employee_list_quotes',{p_token:employee.token,p_search:search.trim()||null});setRows(r||[]);setStatus(r?.length?'':'Chưa có báo giá nào.')}catch(err){setStatus('Không tải được lịch sử: '+String(err))}}
  useEffect(()=>{load()},[])
  async function remove(row:QuoteHistoryRow){if(!confirm(`Xóa báo giá ${row.quote_code}? Thao tác này không thể hoàn tác.`))return;try{await rpc('employee_delete_quote',{p_token:employee.token,p_quote_id:row.id});setStatus('Đã xóa báo giá.');setSelected(null);setEditing(null);await load()}catch(err){setStatus('Không xóa được báo giá: '+String(err))}}
  async function update(){if(!editing)return;if(!editing.customer_name.trim()){setStatus('Tên khách hàng không được để trống.');return}try{const items=(editing.items||[]).map((x:any)=>({...x,quantity:Math.max(1,Number(x.quantity||1)),unit_price:Math.max(0,Number(x.unit_price||0)),line_total:Math.max(1,Number(x.quantity||1))*Math.max(0,Number(x.unit_price||0))}));const total=items.reduce((sum:number,x:any)=>sum+Number(x.line_total||0),0);await rpc('employee_update_quote',{p_token:employee.token,p_quote_id:editing.id,p_customer_name:editing.customer_name.trim(),p_customer_phone:editing.customer_phone.trim(),p_customer_address:editing.customer_address.trim(),p_customer_note:editing.customer_note.trim(),p_items:items,p_total:total});setStatus('Đã cập nhật báo giá.');setEditing(null);setSelected(null);await load()}catch(err){setStatus('Không sửa được báo giá: '+String(err))}}
  function updateItem(index:number,key:'quantity'|'unit_price',value:number){if(!editing)return;const items=[...(editing.items||[])];items[index]={...items[index],[key]:Math.max(key==='quantity'?1:0,value)};setEditing({...editing,items})}
  return <div className="modal-backdrop"><div className="history-panel"><div className="modal-head"><div><h2>Lịch sử báo giá</h2><p>Tài khoản: <b>{employee.username}</b></p></div><button onClick={onClose}><X/></button></div><div className="history-tools"><div><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Tìm tên khách, số điện thoại hoặc mã báo giá"/></div><button onClick={load}><Search size={16}/> Tìm</button></div>{status&&<div className="admin-status">{status}</div>}<div className="history-table"><table><thead><tr><th>Mã báo giá</th><th>Khách hàng</th><th>Số điện thoại</th><th>Tổng tiền</th><th>Ngày tạo</th><th>Thao tác</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.quote_code}</b></td><td>{r.customer_name}</td><td>{r.customer_phone||'-'}</td><td>{money(Number(r.total))}</td><td>{new Date(r.created_at).toLocaleString('vi-VN')}</td><td><div className="history-actions"><button onClick={()=>{setSelected(r);setEditing(null)}}>Xem</button><button onClick={()=>{setEditing({...r,items:(r.items||[]).map(x=>({...x}))});setSelected(null)}}><Pencil size={14}/> Sửa</button><button className="danger" onClick={()=>remove(r)}><Trash2 size={14}/> Xóa</button></div></td></tr>)}</tbody></table></div>{selected&&<QuoteDetail row={selected} onClose={()=>setSelected(null)}/>} {editing&&<div className="quote-edit"><div className="quote-edit-head"><h3>Sửa báo giá {editing.quote_code}</h3><button onClick={()=>setEditing(null)}><X size={16}/></button></div><div className="quote-edit-fields"><label>Tên khách hàng<input value={editing.customer_name} onChange={e=>setEditing({...editing,customer_name:e.target.value})}/></label><label>Số điện thoại<input value={editing.customer_phone} onChange={e=>setEditing({...editing,customer_phone:e.target.value})}/></label><label>Địa chỉ<input value={editing.customer_address} onChange={e=>setEditing({...editing,customer_address:e.target.value})}/></label><label>Ghi chú<input value={editing.customer_note} onChange={e=>setEditing({...editing,customer_note:e.target.value})}/></label></div><div className="quote-edit-items">{(editing.items||[]).map((x:any,i:number)=><div key={i}><span>{x.name}</span><label>SL<input type="number" min="1" value={Number(x.quantity||1)} onChange={e=>updateItem(i,'quantity',Number(e.target.value))}/></label><label>Đơn giá<input type="number" min="0" value={Number(x.unit_price||0)} onChange={e=>updateItem(i,'unit_price',Number(e.target.value))}/></label></div>)}</div><div className="quote-edit-footer"><strong>Tổng mới: {money((editing.items||[]).reduce((sum:number,x:any)=>sum+Math.max(1,Number(x.quantity||1))*Math.max(0,Number(x.unit_price||0)),0))}</strong><button className="primary-inline" onClick={update}><Save size={16}/> Lưu thay đổi</button></div></div>}</div></div>
}

